---
title: "Case Study 0"
format: html
---

```{r}
#| echo: false
#| warning: false
#| message: false 
library(tidyverse)
residents <- read_csv("data/residency.csv") |>
  mutate(period = case_when(
    Year <= 2002 ~ "tp1",
    Year >= 2011 ~ "tp3",
    .default = "tp2"
  ))
```

```{r}
#| echo: false
#| warning: false
#| message: false 
residents$se  <- sqrt(residents$Pct * (1 - residents$Pct) / residents$N)
residents$lwr <- residents$Pct - 2 * residents$se
residents$upr <- residents$Pct + 2 * residents$se
residents$size <- residents$upr - residents$lwr

ggplot(residents, aes(x = Year, y = Pct, color = period)) +
  geom_linerange(aes(ymin = lwr, ymax = upr), linewidth = 0.7) +
  geom_point(size = 2) + 
  labs(title = "independent binomial")

```


```{r}
#| echo: false
#| warning: false
#| message: false 
ggplot(residents, aes(x = Year, y = Pct, color = period)) + 
  geom_point() +
  geom_smooth(method = "lm") + 
  labs(title = "separate regressions")
```

```{r}
#| echo: false
#| warning: false
#| message: false 

fit <- lm(Pct ~ Year * period, data = residents)

pred <- predict(fit, newdata = residents, se.fit = TRUE)

residents$fit   <- pred$fit
residents$se    <- pred$se.fit
residents$lwr   <- residents$fit - 1.96 * residents$se
residents$upr   <- residents$fit + 1.96 * residents$se


ggplot(residents, aes(Year, Pct, color = period, fill = period)) +
  geom_point() +
  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.2, color = NA) +
  geom_line(aes(y = fit), linewidth = 1) +
  labs(title = "interaction model")

```