---
title: "Assignments and grading"
editor: 
  mode: source
---

# Course grade 

Your final course grade breaks down as follows:

- [**10%**] [**Attendance and participation**]{style="color:blue;"}: we will be taking attendance at all class meetings;
- [**15%**] [**Final project**]{style="color:blue;"}: the semester ends with a data analysis project completed *individually*. Details to come;
- [**75%**] [**Case studies**]{style="color:blue;"}: this course is organized around a sequence of case studies where you work in teams to analyze complex, messy datasets coming from various domains. There will be 4 - 6 case studies depending on the pace of course, and they will each get equal weight in determining this course component. *Within* each case study, your grade breaks down as follows:
    - (60%) written report;
    - (30%) presentation;
    - (10%) student-specific collaboration score.

At the end of the semester, your final letter grade will be determined using the usual thresholds:

::: {.center-table}
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |
:::

::: callout-note

These thresholds will not be adjusted upward, but they may be adjusted downward in your favor.

:::

# Case studies 

The case studies are the heart of the class. Case studies will last 2 - 4 weeks depending on complexity, and there will be 4 - 6 in total. Sometimes the class as a whole requests more time to work on the more involved cases, and so we are prepared to be flexible and adjust the pace of the course as needed. Hence, the final number of cases is TBD.

Each case study will go something like this:

- the instructor introduces the data and the research question in lecture;
- students are randomly sorted into teams of 2 - 4. The teams are different for every case study;
- just like in STA 199, we share a GitHub repo with each team that contains the necessary data as well as template Quarto files for your presentation and report;
- working inside their GitHub repo, teams use `R` and `Quarto` to collaborate on a written report and presentation slides;
- during lecture, the instructor introduces new statistical topic that teams may find relevant to the current case study;
- Each case study has two rounds of presentation: an early stage presentation on exploratory work and a final presentation on analysis. Groups will be selected at random to present in one of these two rounds, with each group presenting at least once for each case study;
- Lab sections on Friday will sometimes feature a presentation or tutorial, but for the most part these are built-in work periods where all group members can convene with access to a TA;
- At the end of each case study, students will confidentially evaluate themselves and their group members with a survey through TEAMMATES. **Only the teaching team will have access to this feedback**.

As mentioned above, each case study will be graded as follows:

- (60%) at the end you submit a brief report describing your final analysis;
    - see [here](https://sta440-s26.github.io/syllabus/rubrics/report-rubric.pdf) for the grading rubric;
- (30%) you will give at least one presentation, on your exploratory or final analysis;
    - see [here](https://sta440-s26.github.io/syllabus/rubrics/presentation-rubric.pdf) for the grading rubric;
- (10%) based on your GitHub activity and the results of the TEAMMATES survey, each individual group member will receive a separate score reflecting their contribution to the team's effort.


